#!/usr/bin/perl

sub get_SSHCONFIG ($ID){
  open (SSH_CONFIG, "vagrant ssh-config $ID|") || die $!;
    while (<SSH_CONFIG>){
      s/^ *//g;
      ($key, $value) = split (" ", $_);
      chomp $value;
      $SSH{$key} = $value;
    }
  close (SSH_CONFIG); 
  return %SSH;
}

sub get_IP ($ID){
  $IPLIST = `vagrant ssh $ID -- hostname -I`;
  chomp $IPLIST;
  return $IPLIST;
}

open (STATUS, "vagrant global-status|") || die $!;
  while (<STATUS>) {
    if ( /running/ || /preparing/ ) {
      ( $ID, $NAME, $PROVIDER, $STATE, $DIRECTORY ) = split (/ +/, $_);
      chomp $DIRECTORY;
      $DIRECTORY =~ s/^.*\///g;
      %SSHCONFIG = &get_SSHCONFIG($ID);
      if ( $SSHCONFIG{HostName} =~ /\.amazonaws\.com$/ ){
        $ADDRESS = $SSHCONFIG{HostName};
        $PORT = $SSHCONFIG{Port};
      } else {
        $ADDRESS = &get_IP($ID);
        $ADDRESS = "$SSHCONFIG{HostName} $ADDRESS";
        $PORT = "L_$SSHCONFIG{Port}";
      }
      write;
    }
  }
close STATUS;
print "\n";

format STDOUT_TOP =
======== ========== ====== ======== =========================================
ID       DIRECTORY  PORT   USER     ADDRESSES
======== ========== ====== ======== =========================================
.

format STDOUT =
@<<<<<<< @<<<<<<<<< @>>>>> @<<<<<<< @*
$ID,    $DIRECTORY, $PORT, $SSHCONFIG{User}, $ADDRESS
.
